name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version (e.g. v1.2.3)"
        required: true
        default: "v0.0.1"
      title:
        description: "Release Title"
        required: true
        default: "An update"
      prerelease:
        description: "Is this a pre-release?"
        required: true
        default: true
        type: boolean

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build Binary
        run: |
          mkdir -p build
          gcc -Os -flto -march=native -o build/catsteal-${{ matrix.os }} src/catsteal.c
      - name: Strip Binary
        run: |
          strip build/catsteal-${{ matrix.os }}
      - name: Test Binary
        run: |
          printf '%s\n' "3" | build/catsteal-${{ matrix.os }}
          printf '%s\n' "300" | build/catsteal-${{ matrix.os }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: catsteal-${{ matrix.os }}
          path: build/catsteal-${{ matrix.os }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Generate Checksums
        run: |
          cd dist
          for file in */catsteal-*; do
            sha256sum "$file" > "$file.sha256"
            md5sum    "$file" > "$file.md5"
          done
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.title }}
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            dist/**/catsteal-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
